import numpy as np
from typing import Dict, List, Any, Set

class MetricsEngine:
    """Rigorous event-driven performance metrics engine.
    
    All metrics are calculated strictly from actual simulation event records.
    Never uses hardcoded or simulated mock values.
    """
    def __init__(self, num_bands: int = 50):
        self.num_bands = num_bands
        self.reset()

    def reset(self):
        self.total_scans = 0
        self.signals_intercepted = 0
        self.signals_missed = 0
        self.false_alarms = 0
        
        self.prediction_attempts = 0
        self.prediction_hits = 0
        self.prediction_misses = 0
        self.preemptive_intercepts = 0
        self.unknown_threats_discovered = 0
        
        self.delays: List[int] = []
        self.observed_channels: Set[int] = set()

    def record_step_emissions(self, band: int, detected: bool, is_actually_active: bool, is_false_alarm: bool, num_active_in_world: int, delay: int = 0):
        """Records observation outcomes and accurately tallies world signal interceptions vs misses."""
        self.total_scans += 1
        self.observed_channels.add(band)
        
        if detected and is_actually_active:
            self.signals_intercepted += 1
            self.delays.append(max(0, delay))
            # Any OTHER active signals in the world at this time step were missed by this 1-channel receiver
            if num_active_in_world > 1:
                self.signals_missed += (num_active_in_world - 1)
        else:
            # All active signals in the world at this time step were missed
            self.signals_missed += num_active_in_world
            if detected and is_false_alarm:
                self.false_alarms += 1

    def record_prediction_attempt(self):
        """Records an explicit prediction attempt generated by SAGE."""
        self.prediction_attempts += 1

    def record_prediction_hit(self, is_preemptive: bool = False):
        """Records a successful prediction hit validated against physical emission."""
        self.prediction_hits += 1
        if is_preemptive:
            self.preemptive_intercepts += 1

    def record_prediction_miss(self):
        """Records a prediction attempt that failed to intercept an active signal."""
        self.prediction_misses += 1

    def record_unknown_threat_discovered(self):
        """Records discovery of an uncatalogued threat via exploration."""
        self.unknown_threats_discovered += 1

    @property
    def prediction_accuracy(self) -> float:
        """Cumulative ratio: correct predictions / total predictions."""
        return float(self.prediction_hits / self.prediction_attempts) if self.prediction_attempts > 0 else 0.0

    def get_summary(self, total_emitted_signals: int = 0) -> Dict[str, Any]:
        """Calculates and returns the complete set of 14 benchmark metrics."""
        tot_emissions = max(1, total_emitted_signals)
        
        detection_rate = float(self.signals_intercepted / tot_emissions) if total_emitted_signals > 0 else 0.0
        miss_rate = float(self.signals_missed / tot_emissions) if total_emitted_signals > 0 else 0.0
        
        pred_accuracy = self.prediction_accuracy
        preemptive_rate = float(self.preemptive_intercepts / self.signals_intercepted) if self.signals_intercepted > 0 else 0.0
        
        avg_delay = float(np.mean(self.delays)) if self.delays else 0.0
        channel_coverage = float(len(self.observed_channels) / self.num_bands) if self.num_bands > 0 else 0.0

        return {
            "total_scans": self.total_scans,
            "total_emitted_signals": total_emitted_signals,
            "signals_intercepted": self.signals_intercepted,
            "signals_missed": self.signals_missed,
            "detection_rate": detection_rate,
            "detection_rate_pct": f"{detection_rate * 100:.1f}%",
            "miss_rate": miss_rate,
            "miss_rate_pct": f"{miss_rate * 100:.1f}%",
            "prediction_attempts": self.prediction_attempts,
            "prediction_hits": self.prediction_hits,
            "prediction_misses": self.prediction_misses,
            "prediction_accuracy": pred_accuracy,
            "prediction_accuracy_pct": f"{pred_accuracy * 100:.1f}%",
            "preemptive_intercepts": self.preemptive_intercepts,
            "preemptive_intercept_rate": preemptive_rate,
            "preemptive_intercept_rate_pct": f"{preemptive_rate * 100:.1f}%",
            "avg_detection_latency": avg_delay,
            "avg_delay_label": f"{avg_delay:.1f} slots",
            "channel_coverage": channel_coverage,
            "channel_coverage_pct": f"{channel_coverage * 100:.1f}%",
            "unknown_threats_discovered": self.unknown_threats_discovered,
            "false_alarms": self.false_alarms
        }
